language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - black --check -v expool/ test/
  - flake8 --ignore E501,W503 expool/ test/ --exclude expool/__init__.py
  - mypy .
  - pytest --cov expool/ --cov-report xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
 - bash ./publish.sh
