language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - black --check -v expool/ test/
  - mypy .
  - pytest --cov expool/ --cov-report xml
after_success:
  - bash <(curl -s https://codecov.io/bash)

